# Generated by Django 2.2 on 2022-09-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='quan',
            field=models.IntegerField(),
        ),
    ]
